changelog:
  categories:
    - title: ðŸš€ Features
      labels:
        - feature
    - title: ðŸž Bug Fixes
      labels:
        - bug
    - title: ðŸ”§ Others
      labels:
        - other
  sort: DESC
  exclude:
    labels:
      - ignore
  template: |
    # Changelog

    All notable changes to this project will be documented in this file.

    The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/),
    and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).

    {% for category in categories %}
    ## {{ category.title }}

    {% for label in category.labels %}
    {% assign issues = commits | filter: "labels", label %}
    {% if issues.size > 0 %}
    ### {{ label }}

    {% for issue in issues %}
    - {{ issue.message }} ([#{{ issue.number }}]({{ issue.url }}))
    {% endfor %}
    {% endif %}
    {% endfor %}
    {% endfor %}
