changelog:
  categories:
    - title: ğŸš€ Features
      labels:
        - feature
    - title: ğŸ Bug Fixes
      labels:
        - bug
    - title: ğŸ”§ Others
      labels:
        - other
  sort: DESC
  exclude:
    labels:
      - ignore
  template: |
    {% for category in changelog.categories %}
    ### {{ category.title }}
    {% for pull in category.items %}
    * [{{ pull.title }}]({{ pull.html_url }}) by @{{ pull.author.login }}
    {% endfor %}
    {% endfor %}
