changelog:
  categories:
    - title: ğŸš€ Features
      labels:
        - feature
    - title: ğŸ Bug Fixes
      labels:
        - bug
    - title: ğŸ”§ Others
      labels:
        - other
  sort: DESC
  exclude:
    labels:
      - ignore
