changelog:
  categories:
    - title: ğŸš€ Featuressss
      labels:
        - feature
      change-template: "- [${{CHANGE_TITLE}}](${{CHANGE_URL}}) by @${{AUTHOR}}"
    - title: ğŸ Bug Fixes
      labels:
        - bug
      change-template: "- [${{CHANGE_TITLE}}](${{CHANGE_URL}}) by @${{AUTHOR}}"
    - title: ğŸ”§ Others
      labels:
        - other
      change-template: "- [${{CHANGE_TITLE}}](${{CHANGE_URL}}) by @${{AUTHOR}}"
  sort: DESC
  exclude:
    labels:
      - ignore
